traces_visible = ["United_States_of_America", 
                  "Spain", 
                  "Portugal",
                  "Italy",
                  "France",
                  "China",
                  "Germany",
                  "United_Kingdom",
                  "South_Korea",
                  "Russia",
                  "Australia",
                  "Japan",
                  ]